# Generated by Django 3.0.5 on 2020-04-07 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('affiliation', models.TextField()),
                ('citedby', models.IntegerField()),
                ('pub_title', models.TextField()),
                ('pub_year', models.IntegerField()),
                ('citations', models.IntegerField()),
                ('pub_author', models.TextField()),
                ('eprint', models.TextField()),
            ],
            options={
                'db_table': 'articles',
            },
        ),
    ]
