# Generated by Django 3.0.5 on 2020-04-08 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.TextField()),
                ('affiliation', models.TextField()),
                ('citedby', models.TextField()),
                ('attributes', models.TextField()),
                ('page', models.TextField()),
                ('email', models.TextField()),
                ('interests', models.TextField()),
                ('url_picture', models.TextField()),
            ],
            options={
                'db_table': 'authors',
            },
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
